name: Peass (main) Spring Native Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  runSpringBootNativeDemo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 11, 17 ]
        fail-fast: false
    name: Spring Boot Native Demo ${{ matrix.java }} rcaStrategy UNTIL_SOURCE_CHANGE
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: executeAll
      run: cd spring-boot-nativeTest-demo && ./executeAll.sh main UNTIL_SOURCE_CHANGE
