name: Peass (develop) Spring Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
  schedule:
    - cron: "0 */8 * * *"

jobs:
  runSpringBootDemo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 1.8, 11, 16 ]
        fail-fast: false
    name: Spring Boot Demo ${{ matrix.java }} rcaStrategy UNTIL_SOURCE_CHANGE
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: executeAll
      run: cd spring-boot-demo && ./executeAll.sh develop UNTIL_SOURCE_CHANGE
