# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Build with Peass develop branch

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
  schedule:
    - cron: "0 */8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 1.8, 11, 15 ]
          rcaStrategy: [ COMPLETE, LEVELWISE, UNTIL_SOURCE_CHANGE ]
        fail-fast: false
    name: Java ${{ matrix.java }} rcaStrategy ${{ matrix.rcaStrategy }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: executeAll
      run: cd pure-demo && ./executeAll.sh develop ${{ matrix.rcaStrategy }}
  runSpringBootDemo:
    needs: build
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 1.8, 11, 15 ]
        fail-fast: false
    name: Java ${{ matrix.java }} rcaStrategy ${{ matrix.rcaStrategy }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: executeAll
      run: cd spring-boot-demo && ./executeAll.sh develop UNTIL_SOURCE_CHANGE
