name: Peass (main) Android Demo

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]
  schedule:
    - cron: "0 */8 * * *"

jobs:
  runDemo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 1.8, 11 ] # Java 17 is currently not supported by Android
        fail-fast: false
    name: Android Demo ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: executeAll
      run: cd android-demo && ./executeAll.sh main UNTIL_SOURCE_CHANGE
