name: Peass (main) Android Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  runDemo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 11 ] # Java 17 is currently not supported by Android
        fail-fast: false
    name: Android Demo ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: executeAll
      run: cd android-demo && ./executeAll.sh main UNTIL_SOURCE_CHANGE
