name: Peass (develop) JUnit 3 Demo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: "0 */8 * * *"

jobs:
  runDemo:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          java: [ 17, 21 ]
        fail-fast: false
    name: JUnit 3 Java Demo ${{ matrix.java }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: executeAll
      run: cd demo-junit3 && ./executeAll.sh develop
